Homework #2 and #3 v1.0.0
IgorTitov396/Scala-complete-course pull request #2
Opened 2017-10-05 20:38 UTC by IgorTitov396

2017-10-11 21:26 UTC, vatt2001 commented
Для простоты учета сданных заданий просьба не соединять их вместе в один ПР

2017-10-11 22:58 UTC, vatt2001 requested changes

2017-10-11 22:58 UTC, vatt2001 commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +        case (v1::v3, v2::v4) if (v2 > v1) => merge(v3, Seq[Int](v2) ++ v4, acc ++ Seq[Int](v1))
Ты сам здесь не запутался, что есть что?
У тебя разные по типу значения называются одинаково: v1 и v2 - значения, а v3 и v4 - списки. Пусть уж будет head1, head2, tail1, tail2 или как-нибудь еще.
И если тебе список менять не надо, может вместо `Seq[Int](v2) ++ v4` писать просто `s2`

2017-10-11 22:58 UTC, vatt2001 commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +        case (v1::v3, v2::v4) if (v2 > v1) => merge(v3, Seq[Int](v2) ++ v4, acc ++ Seq[Int](v1))
`acc ++ Seq[Int](v1)` = `acc :+ v1`

2017-10-11 22:58 UTC, vatt2001 commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +        val buf = data.zipWithIndex.partition(_._2 < 5 / 2 - 1)
ой. Что-то с константами ты перемудрил. И еще есть замечательный метод `splitAt`

2017-10-11 22:58 UTC, vatt2001 commented on src/main/scala/lectures/collections/MyListImpl.scala
> +        case _ => List()
К чему такие сложности? вся partial function заменяется на `if (f(value)) List(value) else List()`

2017-10-11 22:58 UTC, vatt2001 commented on src/main/scala/lectures/collections/MyListImpl.scala
> +      case List(value) => f((acc, value))
Зачем отдельно выделять этот случай? Это же комбинация оставшихся двух

2017-10-11 22:58 UTC, vatt2001 commented on src/main/scala/lectures/collections/MyListImpl.scala
> +      case list if (list == Nil) => acc
`case Nil => acc`

2017-10-11 22:58 UTC, vatt2001 commented on src/main/scala/lectures/collections/MyListImpl.scala
> +      case head::tail => MyList(tail).foldLeft(acc + head)(f)
откуда здесь взялось сложение? Мы же не знаем, какая именно операция над аккумулятором делается

2017-10-11 22:58 UTC, vatt2001 commented on src/main/scala/lectures/collections/MyListImpl.scala
> +    def foldLeft(acc: Int)(f: ((Int, Int)) => Int): Int = data match {
Двойные скобки ни к чему: `(f: (Int, Int) => Int)`

2017-10-11 22:58 UTC, vatt2001 commented on src/main/scala/lectures/collections/OptionVsNPE.scala
> +      throw new ResourceException
если была ошибка ResourceException, распечатать "Try again with new resource" и **повторить все заново**

2017-10-11 22:58 UTC, vatt2001 commented on src/main/scala/lectures/functions/Authentication.scala
> +    case _ => false
У тебя получились не partial function, а прям полноценные функции, определенные на всех входных значениях.
А нужно именно PartialFunction. И их уже просто так не вызовешь через apply()

2017-10-11 22:58 UTC, vatt2001 commented on src/main/scala/lectures/functions/Fibonacci.scala
> +    else if (num == 1 || num == 2) 1 else fibs(num - 1) + fibs(num - 2)
Когда подряд идет несколько проверок, обычно принято их объединять в один if-else-if блок. У тебя же проверка с бросанием исключения отвалилась.
И еще в таких случаях не принято писать на одной строке сразу несколько блоков условий.

2017-10-11 22:58 UTC, vatt2001 commented on src/main/scala/lectures/matching/SortingStuff.scala
> +       case List(item: Watches) if item.cost > 1000 => putStuffInRightBox(item, stuffBox)
так ты будешь сортировать только в случае, когда у тебя исходный список stuff будет состоять только из одного элемента.

2017-10-11 22:58 UTC, vatt2001 commented on src/main/scala/lectures/operators/Competition.scala
> +  val results = for (l <- locals.toArray; f <- foreigners) yield l._1 + " vs " + f._1 -> (l._2.toString.toInt - f._2)
Вот такого - не надо: `l._2.toString.toInt`
Лучше упрости формат мапы.

2017-10-11 22:58 UTC, vatt2001 commented on src/main/scala/lectures/operators/EvaluateOptimization.scala
> +  *   последовательности выполнять функции, объединением которых является функция Computations
В функциональном случае так же возникает новая сущность - функция. Которую потом компилятор честно исполняет. Там фишка в другом.

2017-10-11 22:58 UTC, vatt2001 commented on src/test/scala/lectures/functions/FibonacciSpec.scala
> +      it("Should return 28657") {
В описании кейса надо писать, какой случай мы проверяем. То есть, что мы отправляем на вход и что ожидаем получить.

2017-10-11 22:58 UTC, vatt2001 commented on src/test/scala/lectures/operators/CompetitionSpec.scala
> +      it("Should be right") {
Так же - непонятное описание теста. "оно должно работать правильно" - не понятно, что значит "работать правильно"? Разработчик, который придет после тебя, не поймет, что именно здесь проверяется?

2017-10-19 12:37 UTC, IgorTitov396 commented on src/main/scala/lectures/collections/MyListImpl.scala
> +    def foldLeft(acc: Int)(f: ((Int, Int)) => Int): Int = data match {
Я так явно указываю, что подаётся на вход Tuple2, а не 2 параметра.

2017-10-19 13:02 UTC, IgorTitov396 commented on src/main/scala/lectures/matching/SortingStuff.scala
> +       case List(item: Watches) if item.cost > 1000 => putStuffInRightBox(item, stuffBox)
Ну я так и хочу. У меня дальше идёт более общий случай, который создаёт рекурссию:       
case item::rest =>
         val newBox = putStuffInRightBox(item, stuffBox)
         sort(rest, newBox)

2017-10-19 22:31 UTC, vatt2001 commented on src/main/scala/lectures/collections/MyListImpl.scala
> +    def foldLeft(acc: Int)(f: ((Int, Int)) => Int): Int = data match {
ок

2017-10-19 22:42 UTC, vatt2001 requested changes

2017-10-19 22:42 UTC, vatt2001 commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +        case (head1, head2) if (head2.length == 0) => acc ++ head1
`case (head1, Nil) => acc ++ head1`

2017-10-19 22:42 UTC, vatt2001 commented on src/main/scala/lectures/collections/MergeSortImpl.scala
> +        val buf = data.splitAt((list.size + 1) /2)
`val (left, right)) = data.splitAt(...)`

2017-10-19 22:42 UTC, vatt2001 commented on src/main/scala/lectures/functions/Authentication.scala
> +    case CardUser(id, credentials) => AuthenticationData.registeredCards.map(_.cardNumber).contains(credentials.cardNumber)
Так как CardCredentials - это кейс-класс, то в contains можно сравнивать сразу их

2017-10-19 22:42 UTC, vatt2001 commented on src/main/scala/lectures/functions/Authentication.scala
> +    if (Try(authByLP(user)).getOrElse(false) || Try(authByCard(user)).getOrElse(false)) Some(user) else None
Можно скомбинировать две частичные функции и потом уже применить к юзеру

2017-10-19 22:42 UTC, vatt2001 commented on src/main/scala/lectures/matching/SortingStuff.scala
> +       case List(item: Watches) if item.cost > 1000 => putStuffInRightBox(item, stuffBox)
ок

2017-10-19 22:42 UTC, vatt2001 commented on src/main/scala/lectures/operators/Competition.scala
> +  val results = for (l <- locals.toArray.map(pair => (pair._1, toInt(pair._2))); f <- foreigners) yield l._1 + " vs " + f._1 -> (l._2 - f._2)
Чтобы на лету не конвертить данные в массиве, давай ужесточим типизацию массива

2017-10-19 22:42 UTC, vatt2001 commented on src/main/scala/lectures/operators/Competition.scala
> +    else if (r._2 < 0) finalResult -= 1
Два разных стиля написания ++ и --. По возможности надо придерживаться единого стиля

2017-10-19 22:42 UTC, vatt2001 commented on src/main/scala/lectures/operators/EvaluateOptimization.scala
> +  for (1 <- 1 to 100) {
так и не поправил багу

2017-10-20 07:58 UTC, IgorTitov396 commented on src/main/scala/lectures/functions/Authentication.scala
> +    case CardUser(id, credentials) => AuthenticationData.registeredCards.map(_.cardNumber).contains(credentials.cardNumber)
Но сравнение будет по id и credentials, а нам нужно чтобы credentials были равными, а id могут быть разными

2017-10-20 08:01 UTC, IgorTitov396 commented on src/main/scala/lectures/operators/Competition.scala
> +  val results = for (l <- locals.toArray.map(pair => (pair._1, toInt(pair._2))); f <- foreigners) yield l._1 + " vs " + f._1 -> (l._2 - f._2)
Проблема в том, что locals - Map[String, Any]. А по заданию мы не можем менять эту строку. Как обойти это проблему легче я не придумал.

2017-10-20 08:02 UTC, IgorTitov396 commented on src/main/scala/lectures/operators/EvaluateOptimization.scala
> +  for (1 <- 1 to 100) {
Я опять не заметил :)

2017-11-03 16:13 UTC, vatt2001 requested changes

2017-11-03 16:13 UTC, vatt2001 commented on src/main/scala/lectures/functions/Authentication.scala
> +    if (Try((authByCard orElse authByCard)(user)).getOrElse(false)) Some(user) else None
Сразу не увидел, блок Try здесь неуместен: так ты будешь глотать все исключния, даже те, которые тебе надо бы пробрасывать дальше. Используй lift.

2017-11-10 00:03 UTC, vatt2001 requested changes

2017-11-10 00:03 UTC, vatt2001 commented on src/main/scala/lectures/functions/Authentication.scala
> +    }.get) Some(user) else None
Во накрутил... )
Можно и нужно гораздо проще: `(authByCard orElse authByLP).lift.apply(user).getOrElse(false)`. Ну и еще ошибка: нет вызова `authByLP`.
Так же, чтобы было проще писать вычисление `val authenticated`, можно возвращать не Boolean, а `User` (а после `lift` - вообще Option[User], что и требуется по условию).

2017-11-22 18:11 UTC, IgorTitov396 commented on src/main/scala/lectures/functions/Authentication.scala
> +    }.get) Some(user) else None
Done

2017-11-24 14:48 UTC, sergeypopov83 commented on src/main/scala/lectures/matching/SortingStuff.scala
> +       case List(item: Watches) if item.cost > 1000 => putStuffInRightBox(item, stuffBox)
putStuffInRightBox(item, stuffBox) - внутри этого метода нет проверок на стоимость часов, бренд обуви и т.д.

2017-11-24 14:48 UTC, sergeypopov83 commented on src/main/scala/lectures/operators/Competition.scala
>    val locals = Map("Artem" -> 6, "Sergey" -> 5, "Anton" -> 2, "Vladimir" -> "2", "Alexander" -> 4l)
типы были испорчены намеренно. Наверно это  не очень доходчиво написано в постановке

2017-11-24 14:48 UTC, sergeypopov83 commented on src/main/scala/lectures/functions/Fibonacci.scala
> +    if (num < 0) throw new RuntimeException("Fibonacci number not found")
else опять потерялся

2017-11-24 15:16 UTC, IgorTitov396 commented on src/main/scala/lectures/operators/Competition.scala
>    val locals = Map("Artem" -> 6, "Sergey" -> 5, "Anton" -> 2, "Vladimir" -> "2", "Alexander" -> 4l)
https://github.com/IgorTitov396/Scala-complete-course/pull/2/commits/807bfb866fa9ff2c985f4e64b3a3538500437374

2017-11-24 15:28 UTC, IgorTitov396 commented on src/main/scala/lectures/functions/Fibonacci.scala
> +    if (num < 0) throw new RuntimeException("Fibonacci number not found")
Если открыть все изменения, то его видно. magic

2017-11-24 15:32 UTC, IgorTitov396 commented on src/main/scala/lectures/matching/SortingStuff.scala
> +       case List(item: Watches) if item.cost > 1000 => putStuffInRightBox(item, stuffBox)
Проверка же есть в sort

2017-12-06 12:26 UTC, merged