Homework #5 v0.1.0
IgorTitov396/Scala-complete-course pull request #4
Opened 2017-10-30 14:17 UTC by IgorTitov396

My solution for HW #5

2017-11-02 23:32 UTC, vatt2001 requested changes

2017-11-02 23:32 UTC, vatt2001 commented on src/main/scala/lectures/oop/BST.scala
> +      if (left.isDefined) this.copy(left = Option(left.get.add(newValue).asInstanceOf[BSTImpl])) else this.copy(left = Option(BSTImpl(newValue)))
`if (left.isDefined) ... left.get ... else ...` эквивалентно выражению `left.map(...).getOrElse`

2017-11-02 23:32 UTC, vatt2001 commented on src/main/scala/lectures/oop/BST.scala
> +      if (left.isDefined) this.copy(left = Option(left.get.add(newValue).asInstanceOf[BSTImpl])) else this.copy(left = Option(BSTImpl(newValue)))
Оборачивать в Option имеет смысл только если тебе надо защититься от null-ов. Если защищаться не надо, то оборачивай сразу в Some

2017-11-02 23:32 UTC, vatt2001 commented on src/main/scala/lectures/oop/BST.scala
> +    else if (value > this.value) right
Не факт, что справа будет нужно значение.

2017-11-02 23:32 UTC, vatt2001 commented on src/main/scala/lectures/oop/BST.scala
> +  override def toString: String = {
Попробуй переписать рекурсивно, через вызовы toString у поддеревьев и потом объединения их в общий toString для данного узла

2018-01-14 17:36 UTC, IgorTitov396 commented on src/main/scala/lectures/oop/BST.scala
> +  override def toString: String = {
fix

2018-01-15 15:02 UTC, sergeypopov83 commented on src/main/scala/lectures/oop/BST.scala
> +          left = Some(bst_left.add(newValue).asInstanceOf[BSTImpl])
для избежания .asInstanceOf[BSTImpl]) обычно делают приватную реализацию типа addImpl: BSTImpl

2018-01-16 12:40 UTC, sergeypopov83 commented on src/main/scala/lectures/oop/BST.scala
> +      )( bst_left =>
в scala действует ковнвенция, что переменные называются в camel case

2018-01-16 12:40 UTC, sergeypopov83 commented on src/main/scala/lectures/oop/BST.scala
> +          left = Some(bst_left.add(newValue).asInstanceOf[BSTImpl])
для того что бы не было asInstanceOf нужно отделить методы- имплементации от интерфейсных
т.к. надо завести addImpl : BSTIMpl и сипользовать его. А метод def add(v): BST  = addImpl(v)

2018-01-16 12:40 UTC, sergeypopov83 commented on src/main/scala/lectures/oop/BST.scala
> +    implicit class MyRichString(str: String) {
не стоит создавать класс внутри метода. Это создает новый тип при каждом вызове метода. Ты так можешь вырастить permGen до сумасшедших размеров

2018-01-16 12:40 UTC, sergeypopov83 commented on src/main/scala/lectures/oop/BST.scala
> +        str.normalizeWidth(width).normalizeHeight(height)
Смотри, у тебя каждый вызов метода MyRichString типа normalizeWidth(width) создает заново инстанс это неправильно

2018-01-18 14:30 UTC, IgorTitov396 commented
Fix

2018-02-19 21:34 UTC, vatt2001 approved these changes

2018-02-19 21:35 UTC, merged